// Generated by LiveScript 1.3.0
(function(){
  var $PP, $SHAPE, renderShape, renderBg, fill, handleFile;
  $PP = [
    {
      p1: "258,0 519,150 519,450 0,150",
      p2: "519,450 258,600 0,450 0,150"
    }, {
      p1: "258,0 519,150 519,450 258,600",
      p2: "258,0 258,600 0,450 0,150"
    }, {
      p1: "519,150 519,450 258,600 0,450",
      p2: "258,0 519,150 0,450 0,150"
    }, {
      p1: "",
      p2: "258,0 519,150 519,450 258,600 0,450 0,150"
    }
  ];
  $SHAPE = 0;
  renderShape = function(){
    $('#p1').attr('points', $PP[$SHAPE].p1);
    return $('#p2').attr('points', $PP[$SHAPE].p2);
  };
  renderBg = function(){
    var c1, c2, b1, b2, tc;
    c1 = tinycolor($('#p1').css('fill'));
    c2 = tinycolor($('#p2').css('fill'));
    b1 = c1.getBrightness();
    b2 = c2.getBrightness();
    if (b1 > b2) {
      tc = tinycolor({
        r: 255 - b1,
        g: 255 - b1,
        b: 255 - b1
      });
    } else {
      tc = tinycolor({
        r: 255 - b2,
        g: 255 - b2,
        b: 255 - b2
      });
    }
    $('body').stop();
    return $('body').animate({
      'background-color': tc.darken().toHexString()
    }, 500);
  };
  fill = function(polyId, hex){
    $("#" + polyId).attr('fill', "#" + hex);
    $("#" + polyId).attr('stroke', "#" + hex);
    $("#c" + polyId).css('border-color', "#" + hex);
    $("#c" + polyId).css('color', "#" + hex);
    $("#c" + polyId).css('background-color', "#" + hex);
    return renderBg();
  };
  handleFile = function(file){
    var img, reader;
    if (file.type.match(/image.*/)) {
      img = $('#image-select img')[0];
      img.file = file;
      reader = new FileReader();
      reader.onload = function(e){
        img.src = e.target.result;
        return $('#canvas image').attr('xlink:href', e.target.result);
      };
      return reader.readAsDataURL(file);
    } else {
      return console.log('not-img');
    }
  };
  $(function(){
    var colorPicker1, colorPicker2;
    colorPicker1 = '#cp1';
    colorPicker2 = '#cp2';
    $(colorPicker1).colpick({
      submit: false,
      layout: 'hex',
      colorScheme: 'dark',
      onChange: function(hsb, hex, rgb, el){
        return fill('p1', hex);
      }
    });
    $(colorPicker2).colpick({
      submit: false,
      layout: 'hex',
      colorScheme: 'dark',
      onChange: function(hsb, hex, rgb, el){
        return fill('p2', hex);
      }
    });
    $(colorPicker1).colpickSetColor('fec605');
    $(colorPicker2).colpickSetColor('fea66c');
    renderShape();
    $('#shape-select').on('click', function(){
      var ref$;
      $SHAPE = ((($SHAPE + 1) % (ref$ = $PP.length) + ref$) % ref$);
      renderShape();
      if ($SHAPE === 3) {
        return $('#cp1').addClass('disabled');
      } else {
        return $('#cp1').removeClass('disabled');
      }
    });
    $('#image-select').on('click', function(){
      return $('#upload-image').trigger('click');
    });
    $('#upload-image').on('change', function(){
      var file;
      file = $('#upload-image')[0].files[0];
      console.log(file);
      return handleFile(file);
    });
    return $('#download').on('click', function(){
      var svg;
      svg = "<svg>" + $('#canvas').html() + "</svg>";
      return canvg(document.getElementById('buffer'), svg, {
        log: true,
        renderCallback: function(){
          window.open(document.getElementById('buffer').toDataURL(), "title", "width=520px, height=600px");
        }
      });
    });
  });
}).call(this);
